### ISSUE TITLE
Apollo Dateset problem

### ISSUE THREAD

**Issue by ljxxxxxxxxxxxx** [DuncanZauss/Keypoint_Communities#15]
I downloaded the apollo dataset , but why there is no folder "ignore_mask" in it?

**Comment by DuncanZauss** [comment]
For the apollo dataset there are now areas, which are ignored, so this folder is not needed. The dataloading should work just fine also without these masks.
For MS COCO there are ignore masks areas, because there are sometimes areas where it is unclear what the ground truth poses are, i.e. very crowded areas or blurry areas in the images. For these areas no gradient is back propagated.
